name: FIRE_SAC
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=openblas
  - ca-certificates=2025.7.15=h06a4308_0
  - filelock=3.17.0=py39h06a4308_0
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py39h5eee18b_0
  - jinja2=3.1.6=py39h06a4308_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libegl=1.7.0=ha4b6fd6_2
  - libffi=3.3=h58526e2_2
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.68.4=h3e27bee_0
  - libglu=9.0.3=h03adeef_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libopenblas=0.3.29=ha39b09d_0
  - libpciaccess=0.18=hd590300_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libxcb=1.17.0=h8a09558_0
  - libzlib=1.2.13=h4ab18f5_6
  - markupsafe=3.0.2=py39h5eee18b_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.2.1=py39h06a4308_0
  - openblas=0.3.4=ha44fe06_0
  - openssl=1.1.1w=h7f8727e_0
  - pcre=8.45=h9c3ff4c_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.9.0=hffdb5ce_5_cpython
  - pytorch=2.3.1=cpu_py39h4f03144_0
  - readline=8.2=h8c095d6_2
  - setuptools=75.8.2=pyhff2d567_0
  - sqlite=3.46.0=h6d4b2fc_0
  - sympy=1.14.0=py39h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libx11=1.8.11=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - zlib=1.2.13=h4ab18f5_6
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - appdirs==1.4.4
      - arch==7.2.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - chex==0.1.86
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==0.29.37
      - debugpy==1.8.13
      - decorator==4.4.2
      - defusedxml==0.7.1
      - dm-control==1.0.20
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - dotmap==1.3.30
      - etils==1.5.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - flax==0.8.5
      - fonttools==4.56.0
      - fqdn==1.5.1
      - fsspec==2025.2.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.8.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - gymnasium-robotics==1.3.1
      - gymnax==0.0.6
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.34.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipdb==0.13.13
      - ipykernel==6.29.5
      - ipython==8.18.1
      - isoduration==20.11.0
      - jax==0.4.30
      - jax-cuda12-pjrt==0.4.30
      - jax-cuda12-plugin==0.4.30
      - jaxlib==0.4.30
      - jaxopt==0.8.3
      - jedi==0.19.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - labmaze==1.0.6
      - lxml==5.3.1
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.2
      - ml-dtypes==0.5.1
      - moviepy==1.0.3
      - msgpack==1.1.0
      - mujoco==3.1.6
      - mujoco-py==2.1.2.14
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numpy==1.24.1
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvcc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-nccl-cu12==2.25.1
      - nvidia-nvjitlink-cu12==12.8.61
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - optax==0.2.2
      - orbax-checkpoint==0.5.18
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patchelf==0.17.2.2
      - patsy==1.0.1
      - pettingzoo==1.25.0
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - proglog==0.1.10
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==4.25.6
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.19.1
      - pyopengl==3.1.9
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - referencing==0.36.2
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rliable==1.2.0
      - rpds-py==0.23.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shimmy==2.0.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - tensorflow-probability==0.24.0
      - tensorstore==0.1.69
      - termcolor==2.4.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.2.1
      - toolz==1.0.0
      - tornado==6.4.2
      - tqdm==4.66.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wandb==0.16.6
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - zipp==3.21.0
